add classification route
Project-4AHIF-JP-FG-BH-TF/wiki pull request #8
Opened 2024-03-12 11:08 UTC by ToBinio

2024-03-13 18:15 UTC, xFizzar requested changes
requested change

2024-03-13 18:15 UTC, xFizzar commented on routes/node/log.md
on Line 37 it still says that the classification is either 'info' or 'error'. It can be a string tough.
```
classification: "info" | "error";
```

Suggestion:

```
classification: string;
```

2024-03-19 07:56 UTC, ToBinio commented on routes/node/log.md
done

2024-03-20 10:23 UTC, xFizzar approved these changes
lgtm

2024-03-20 10:24 UTC, merged